// Copyright 2022 Team Havtorn. All Rights Reserved.

#pragma once

#include "ECS/Entity.h"
#include "ECS/Component.h"
#include "ECS/ComponentView.h"
#include "ECS/System.h"

#include "ECS/Systems/RenderSystem.h"
#include "ECS/Systems/CameraSystem.h"
#include "ECS/Systems/LightSystem.h"
#include "ECS/Systems/DebugShapeSystem.h"
#include "ECS/Systems/SpriteAnimatorGraphSystem.h"
#include "ECS/Systems/SequencerSystem.h"
#include "../HexPhys/HexPhys.h"

#include "ECS/Components/TransformComponent.h"
#include "ECS/ComponentViews/TransformComponentView.h"
#include "ECS/Components/StaticMeshComponent.h"
#include "ECS/ComponentViews/StaticMeshComponentView.h"
#include "ECS/Components/CameraComponent.h"
#include "ECS/ComponentViews/CameraComponentView.h"
#include "ECS/Components/CameraControllerComponent.h"
#include "ECS/ComponentViews/CameraControllerComponentView.h"
#include "ECS/Components/MaterialComponent.h"
#include "ECS/ComponentViews/MaterialComponentView.h"
#include "ECS/Components/EnvironmentLightComponent.h"
#include "ECS/ComponentViews/EnvironmentLightComponentView.h"
#include "ECS/Components/DirectionalLightComponent.h"
#include "ECS/ComponentViews/DirectionalLightComponentView.h"
#include "ECS/Components/PointLightComponent.h"
#include "ECS/ComponentViews/PointLightComponentView.h"
#include "ECS/Components/SpotLightComponent.h"
#include "ECS/ComponentViews/SpotLightComponentView.h"
#include "ECS/Components/VolumetricLightComponent.h"
#include "ECS/ComponentViews/VolumetricLightComponentView.h"
#include "ECS/Components/DecalComponent.h"
#include "ECS/ComponentViews/DecalComponentView.h"
#include "ECS/Components/SpriteComponent.h"
#include "ECS/ComponentViews/SpriteComponentView.h"
#include "ECS/Components/Transform2DComponent.h"
#include "ECS/ComponentViews/Transform2DComponentView.h"
#include "ECS/Components/SpriteAnimatorGraphComponent.h"
#include "ECS/ComponentViews/SpriteAnimatorGraphComponentView.h"
#include "ECS/Components/SequencerComponent.h"
#include "ECS/ComponentViews/SequencerComponentView.h"
#include "ECS/Components/Physics2DComponent.h"
#include "ECS/ComponentViews/Physics2DComponentView.h"
#include "ECS/Components/Physics3DComponent.h"
#include "ECS/ComponentViews/Physics3DComponentView.h"
#include "ECS/Components/Physics3DControllerComponent.h"
#include "ECS/ComponentViews/Physics3DControllerComponentView.h"
#include "ECS/Components/DebugShapeComponent.h"
#include "ECS/Components/MetaDataComponent.h"
